 version: '2'
 services:
   misic-app:
     build: 
      context: "./"
      dockerfile: "Dockerfile"
     ports:
     - "80:3000"
     depends_on:
     - "db"
     command: ["sh","./bin/run.sh"]
   db:
     ports:
     - "27017:27017"
     image: "mongo"
