version: '2'
services:
  music-app:
    build: .
    ports:
     - "80:3000"
	depends_on:
      - mongo
	command: ["./wait-for-it.sh", "localhost:27017", "--", "npm", "start"]
  mongo:
    image: "mongo"